### ISSUE TITLE
FNA Assembly not found after .exe modify

### ISSUE THREAD

**Issue by Sese-Schneider** [ShootMe/CelesteTAS#10]
After modifying the exe according to your documentation, the following error is logged:

```
System.IO.FileNotFoundException: Could not load file or assembly "FNA, Version=18.1.2.0, Culture=neutral, PublicKeyToken=null" or one of its dependencies. The located assembly's manifest definition does not match the assembly reference.

Filename: "FNA, Version=18.1.2.0, Culture=neutral, PublicKeyToken=null"
   at Monocle.Engine.Update(GameTime gameTime)
   at Celeste.Celeste.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Monocle.Engine.RunWithLogging()
```

**Comment by ShootMe** [comment]
Needed to use correct Celeste-Addons.dll

**Comment by 2403772980ygy** [comment]
> Needed to use correct Celeste-Addons.dll

Well I've got the same problem, do you mean to XNA version ans the OpenGL version?

Note: After I changed the Celeste-Addons.dll to the XNA version. It still goes bad......
